#!/home/steve/google-assistant/env/bin/python
# -*- coding: utf-8 -*-
import re
import sys
import os
from googlesamples.assistant.hotword.hotword import main

os.chdir("../lib/python3.9/site-packages/googlesamples/assistant/hotword/")

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
